# Generated by Django 4.2.6 on 2024-07-09 14:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Текст'),
        ),
    ]
