# Generated by Django 4.2.6 on 2024-07-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='content',
        ),
    ]
