# Generated by Django 4.2.6 on 2024-07-08 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_place_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_imgs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_imgs', to='places.image', verbose_name='Фотографии'),
        ),
    ]
