# Generated by Django 4.2.6 on 2024-07-08 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_image_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='position',
        ),
    ]
