# Generated by Django 4.2.6 on 2024-07-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_place_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imgs',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Фото'),
        ),
    ]
