# Generated by Django 4.2.6 on 2024-07-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_description_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imgs',
            new_name='img',
        ),
    ]
